### ISSUE TITLE
Add section landing pages

### ISSUE THREAD

**Issue by geealbers** [thegetty/living-matter#20]
Each of the five sections of the book need a landing page. In each section, created a `section-contents.md` file with YAML as in the below example. The title, subtitle and weight will change for each one, but the other values will stay the same. Use the section titles as they can be found in the LivingMatter_FM1_TOC.docx transmittal file on the server, but note that in that document they're all uppercase, but should be converted to title case for publication.

```yaml
---
title: Living Matter in Contemporary Art
subtitle: Snapshots
type: contents
class: abstract
slug: .
weight: 19
---
```
