### ISSUE TITLE
Review PDF output and make adjustments to figure size and border

### ISSUE THREAD

**Issue by geealbers** [thegetty/living-matter#34]
For any figure or figure group that should be enlarged in the PDF to span both columns of text, add `class="pdf-two-column"` to the shortcode.

For any figure that could use a thin border around it in both screen and PDF, add `class="figure-border"` to the shortcode. There may or may not be any that need this.

If there are instances where a figure should be larger and have a border, the classes can be combined with a space between them: `class="pdf-two-column figure-border"`

---

And I realized we also need to add the corresponding CSS styles in for these to. For that, add the following to the bottom of the`static/custom.css` file. Under the `/* FIGURE & TABLES` heading to keep it organized. 

```css
.quire-figure.pdf-two-column {
    column-span: all;
 }
.quire-figure.figure-border img {
    border: 1px solid #333;
 }
```
