### ISSUE TITLE
 Convert Word files to Markdown and add to project

### ISSUE THREAD

**Issue by geealbers** [thegetty/living-matter#8]
## 1. Convert 

Pull the transmittal files for all the essays from the department server at /Volumes/DEPT/Pubs/ILLUSTRATIONS/GCI/16674 Living Matter Preservation Bio/Transmittal Manuscript, and convert them to Markdown. There are instructions for converting with Pandoc and using the command line at: https://quire.getty.edu/documentation/fundamentals/#microsoft-word-to-markdown-conversion.

## 2. Check formatting

Once converted, you should look over them to see if they seemed to have converted cleanly (are headings correct, were italic preserved, are footnotes there, etc.). You'll also need to do some formatting of the page YAML which the copyeditor has given us a great start on in each file. There's a sample below, just note that you'll need to change their `number` to `weight` and probably also change the number itself. Move `short_title` up to below `subtitle` just to keep those elements near one another. Add `type: essay`, and watch the indenting for the contributors, and the abstract. Also a good idea to surround the bios and abstract in straight double quotes to avoid and formatting issues.

```yaml
weight: 10
title: In the Unpredictable Garden of Forking Paths
subtitle: 
short_title: In the Unpredictable Garden
type: essay
contributor:
  - first_name: Adrián 
    last_name: Villar Rojas
    bio: "Adrián Villar Rojas creates immersive, situated, and perishing worlds using materials both organic and inorganic, human-made and machine-made, that undergo change over time. Tied to their production and exhibiting contexts, these worlds generate irreproducible experiences relying on collaborative exchange between the artist, his team, and local agents. His projects that extend over open-ended periods of time allow him to question the aftermath of the normalized production of art in the Capitalocene era. He lives and works nomadically."
  - first_name: Sebastián
    last_name: Villar Rojas
    bio: "Sebastián Villar Rojas is a writer, playwright, and theater director who is currently generating “androgynous” projects that inhabit the borderline between artistic fields, taking advantage of the ontological ambiguity of this liminal zone. He studied political science at the Universidad Nacional de Rosario, Argentina, and holds a diploma in playwriting from the School of Philosophy and Letters, Universidad de Buenos Aires."
abstract: "From suicidal or ephemeral sculptures to diachronic, mutant, or hybrid objects, the presence of the living in my projects has been developing for more than a decade. In this essay, I attempt to provide a panoramic overview of this journey, while showing how each phase of this relationship with living matter causes my team’s collaborative work to be organized differently. I will follow a chronological order in coordination with theoretical considerations, many of which emerged in interviews, books, and catalogues written together with my brother Sebastián, a writer, playwright, and theater director. Accordingly, the notion of praxis fits in well with my own practice, which is affected both by contingent discovery and by the intention to formalize it in idea systems."
```

## Add to Project

Once the conversions are all done, you'll want to add them into the project repo, following the structure @TevvyBall has in the Table of Contents (which is also part of the transmittal files). Note that this book as some sub-sections. For those, create folders to contain each set of files within the sub-section. I think the end result will look something like this:

```
cover.md
copyright.md
foreword.md
preface.md
00.md
snapshots
  01.md
  02.md
  03.md
  04.md
  05.md
  06.md
artists
  07.md
  08.md
  09.md
  10.md
institutions
  11.md
  12.md
  13.md
  14.md
  15.md
  16.md
approaches
  17.md
  18.md
  19.md
  20.md
  21.md
reflections
  22.md
  23.md
  24.md
bibliography.md
contributors.md
participants.md
about.md
```
